// Generated by Wrangler by running `wrangler types`

interface Env {
	TELEGRAM_BOT_TOKEN?: string;
	SECRET_TELEGRAM_API_TOKEN?: string;
	AI_API_KEY?: string;
	OPENAI_API_KEY?: string;
	GEMINI_API_KEY?: string;
	account_id?: string;
	AI_BASE_URL?: string;
	AI_MODEL?: string;
	BASE_URL?: string;
	MODEL?: string;
	DB: D1Database;
}
