// Generated by Wrangler by running `wrangler types`

interface Env {
	TELEGRAM_BOT_TOKEN?: string;
	SECRET_TELEGRAM_API_TOKEN?: string;
	AI_API_KEY?: string;
	OPENAI_API_KEY?: string;
	GEMINI_API_KEY?: string;
	ADMIN_USER_IDS?: string;
	ADMIN_USER_ID?: string;
	AI_BASE_URL?: string;
	AI_MODEL?: string;
	BASE_URL?: string;
	MODEL?: string;
	SYSTEM_PROMPT_SUMMARY?: string;
	SYSTEM_PROMPT_ASK?: string;
	LIMIT_SUMMARY?: string;
	LIMIT_ASK?: string;
	LIMIT_QUERY?: string;
	USER_DAILY_LIMIT?: string;
	LIMIT_GROUP_MESSAGES?: string;
	GROUP_MESSAGE_LIMIT?: string;
	LIMIT_GROUP_IMAGES?: string;
	GROUP_IMAGE_LIMIT?: string;
	REASONING_EFFORT?: string;
	DB: D1Database;
}
